<?php

namespace Kendoctor\Bundle\DocumentorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentVersionRepository extends EntityRepository {

    public function getVersionByDocumentHash($hash) {

        $query = $this->_em->createQuery("
            SELECT v 
            FROM KendoctorDocumentorBundle:DocumentVersion v
            WHERE v.documentHash = :hash
            ")->setParameter("hash", $hash)
        ;

        return $query->getOneOrNullResult();
    }

    public function getVersionOfDocumentWithLang($versionId, $lang) {

        $query = $this->_em->createQuery("
            SELECT v
            FROM KendoctorDocumentorBundle:DocumentVersion v
            JOIN v.document d
            LEFT JOIN d.translations t
            WHERE v.id = :id ")->setParameter("id", $versionId)
        ;

        //  $query->setHint(Gedmo\TranslationListener::HINT_TRANSLATABLE_LOCALE, $lang);
        return $query->getOneOrNullResult();
    }

    public function getVersionOfDocumentForLang($version, $lang)
    {
    
        $query = $this->_em->createQuery("
            SELECT v
            FROM KendoctorDocumentorBundle:DocumentVersion v
            JOIN v.document d
            LEFT JOIN d.translations t
            WHERE d.id = :documentId AND v.version = :version AND v.lang = :lang
            ")->setParameter("documentId", $version->getDocument()->getId())
                ->setParameter("version", $version->getVersion())
                ->setParameter("lang", $lang)
        ;
        
//echo $query->getSQL();exit;
      // $query->setHint(\Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE, $lang);
        return $query->getOneOrNullResult();
    }
}
