<?php

namespace Kendoctor\Bundle\DocumentorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository {

    public function getLanguagesOfDocument($id) {
        $query = $this->_em->createQuery("
            SELECT DISTINCT(ct.locale) AS lang
            FROM KendoctorDocumentorBundle:ContentTranslation ct
            WHERE ct.object =  :id
            ")->setParameter("id", $id);
        return $query->getScalarResult();
    }

 
}
